// =====================================================================
// class_orbits.m  --  b(pi, phi) by orbits on conjugacy classes of N
// =====================================================================
//
// Requires (load first): records.m, embedding_problems.m
//
// SHARED BY BOTH ORDERINGS.  The two orderings differ only in which
// non-identity conjugacy classes of N = Ker(pi) are counted:
//
//   disc   classes whose representative g has ind(g) = ind(G)
//   prp    every non-identity class
//
// so each orbits.m just supplies a "keep" predicate and everything below is
// common.  The predicate MUST be invariant under G-conjugation and under
// powering by integers prime to d, which holds for ind (cycle type is
// preserved) and trivially for "g ne 1".  An assert below checks this
// invariance on every image it computes, so a bad predicate fails loudly.
//
// WHY CLASSES OF N ARE ENOUGH.  G(pi,phi) is generated by N x 1 and by one
// element (x_c, c) for each generator c of C, with pi(x_c) = phi(c).  N x 1
// acts trivially on N-classes, and G(pi,phi) / (N x 1) is isomorphic to C
// via (x, y) -> y.  So the orbits of G(pi,phi) on the ELEMENTS of
// Smin meet N are in bijection with the orbits of C on the N-classes they
// form, with c acting by [g] -> [x_c^-1 g^f(c) x_c].
//
// THE CACHE.  That action splits into two permutations of class indices,
// both cacheable per pi:
//
//   POWERING     P_a : [g] -> [g^a], depends only on the generator c of C;
//   CONJUGATION  C_b : [g] -> [x^-1 g x] with pi(x) = b, depends only on b
//                in B (conjugation by N fixes every N-class), and
//                C_{x1 x2} = C_{x2} . C_{x1}; B is abelian, so [G,G] <= N
//                and the order of composition does not matter.
//
// So per pi we pay (Ngens(B) + Ngens(C)) * #kept-classes ClassMap
// evaluations, once, and each pair is pure array work.  The permutations are
// built on the KEPT classes only, so for the disc ordering nothing is spent
// on classes of the wrong index.

ClassOrbitCtx := recformat<
    N,          // Kernel(pi)
    nkept,      // number of kept N-classes (0 => nothing to count)
    setsize,    // number of ELEMENTS in the kept classes
    Cgens,      // generators of C, in a fixed order
    powperm,    // powperm[k] = P_{a_k} on kept-class positions
    conjperm,   // conjperm[j] = C_{x_j} for the j-th generator of B
    Bgens,      // generators of B, in the matching order
    Border      // their orders
>;

// keepfn : element of N -> BoolElt.  Called once per class of N.
MakeClassOrbitCtx := function(ebp, keepfn)
    N := Kernel(ebp`pi);
    if #N eq 1 then
        return rec< ClassOrbitCtx | N := N, nkept := 0, setsize := 0 >;
    end if;

    G := ebp`G; B := ebp`B; C := ebp`C; f := ebp`f; pi := ebp`pi;
    cls  := Classes(N);
    keep := [ i : i in [1..#cls] | keepfn(cls[i][3]) ];
    if #keep eq 0 then
        return rec< ClassOrbitCtx | N := N, nkept := 0, setsize := 0 >;
    end if;

    cm  := ClassMap(N);
    pos := [ 0 : i in [1..#cls] ];
    for k := 1 to #keep do pos[keep[k]] := k; end for;
    K := #keep;

    Cgens := [ c : c in Generators(C) ];
    powperm := [];
    for k := 1 to #Cgens do
        a := IntegerRing()!(f(Cgens[k]));
        row := [];
        for t := 1 to K do
            q := pos[cm((cls[keep[t]][3])^a)];
            assert q ne 0;   // keep predicate not invariant under powering
            Append(~row, q);
        end for;
        Append(~powperm, row);
    end for;

    Bgens := [ B.j : j in [1..Ngens(B)] ];
    conjperm := [];
    for j := 1 to #Bgens do
        xg := G!(Bgens[j] @@ pi);
        xi := xg^(-1);
        row := [];
        for t := 1 to K do
            q := pos[cm(xi * (cls[keep[t]][3]) * xg)];
            assert q ne 0;   // keep predicate not invariant under conjugation
            Append(~row, q);
        end for;
        Append(~conjperm, row);
    end for;

    return rec< ClassOrbitCtx |
        N := N, nkept := K,
        setsize := &+[ cls[i][2] : i in keep ],
        Cgens := Cgens, powperm := powperm,
        conjperm := conjperm, Bgens := Bgens,
        Border := [ Order(b) : b in Bgens ] >;
end function;

// C_b for an arbitrary b in B, composed from the cached generator
// permutations.  Pure array work.
ClassConjPermForB := function(ctx, b)
    K := ctx`nkept;
    perm := [ i : i in [1..K] ];
    e := Eltseq(b);
    for j := 1 to Minimum(#e, #ctx`conjperm) do
        m := e[j] mod ctx`Border[j];
        for t := 1 to m do
            perm := [ ctx`conjperm[j][perm[i]] : i in [1..K] ];
        end for;
    end for;
    return perm;
end function;

// Returns (number of elements in the counted set, number of orbits).
ClassOrbitCount := function(ebp, ctx)
    if ctx`nkept eq 0 then return 0, 0; end if;
    K := ctx`nkept;

    // One permutation per generator of C: power, then conjugate.
    actperms := [];
    for k := 1 to #ctx`Cgens do
        cp := ClassConjPermForB(ctx, ebp`phi(ctx`Cgens[k]));
        pp := ctx`powperm[k];
        Append(~actperms, [ cp[pp[i]] : i in [1..K] ]);
    end for;

    visited := [ false : i in [1..K] ];
    orbits := 0;
    for i := 1 to K do
        if visited[i] then continue; end if;
        orbits +:= 1;
        visited[i] := true;
        queue := [i];
        idx := 1;
        while idx le #queue do
            curr := queue[idx];
            idx +:= 1;
            for p in actperms do
                nxt := p[curr];
                if not visited[nxt] then
                    visited[nxt] := true;
                    Append(~queue, nxt);
                end if;
            end for;
        end while;
    end for;
    return ctx`setsize, orbits;
end function;
