// =====================================================================
// Three-valued local verdicts
// =====================================================================
//
// Requires (load first): records.m, local_tame.m, wild_prop.m
//
// WHY THREE VALUES.  The old code asked one boolean question, "do the local
// tests pass?", and used a false answer to veto a pair out of the b_W upper
// bound.  That is only legitimate when a failed test PROVES local
// insolvability, and two of the tests do not prove it:
//
//  (T) TAME TEST AT A PRIME p WHERE F/Q IS TAME.  It searches for X,Y in G
//      with pi(X)=bX, pi(Y)=bY and X*Y*X^-1 = Y^p, i.e. for a lift that
//      factors through the TAME quotient of G_{Q_p}.  A lift sends wild
//      inertia into a p-subgroup of N, so when p does not divide #N that
//      subgroup is trivial and the tame test is exact in both directions.
//      When p | #N the lift may be genuinely wildly ramified, and a failed
//      tame test proves nothing.
//
//  (W) PRO-p TEST AT A PRIME WHERE F/Q IS WILD.  Success exhibits a lift of
//      G_{Q_p}(p) -> Dp, where Dp is the image of the maximal pro-p quotient.
//      That is a lift of phi_p itself only when phi_p factors through
//      G_{Q_p}(p), i.e. when the FULL local image phi_p(G_{Q_p}) is a
//      p-group -- which is checkable, and is checked below.  In the other
//      direction, whether a full local lift forces the pro-p problem to be
//      solvable is not established (a full lift need not have p-group image
//      and need not factor through G_{Q_p}(p)), so a failed pro-p test is
//      recorded as undetermined.
//
// So each place returns one of
//
//      LocalVerdictYes      a lift at this place has been EXHIBITED
//      LocalVerdictNo       no lift at this place exists, PROVEN
//      LocalVerdictUnknown  neither
//
// and the two consumers read it differently:
//
//   * the b_W UPPER bound excludes a pair only on a No;
//   * a certificate that needs local solvability everywhere (certificates/
//     central.m) fires only on an all-Yes, since Yes is the direction that
//     actually produces a lift.
//
// POLICY.  DefaultLocalPolicy is the sound reading above.  LegacyLocalPolicy
// reproduces the pre-refactor behaviour, in which (T) with p | #N and (W)
// both veto.  Legacy is retained ONLY so that diagnose_policy.m can measure
// how many published cells the correction moves; do not compute with it.
//
// Policy is threaded as an argument rather than read from a global: Magma
// captures free identifiers when a function is DEFINED, so a global flipped
// after load time would not be seen by anything already defined.

LocalVerdictYes     :=  1;
LocalVerdictUnknown :=  0;
LocalVerdictNo      := -1;

LocalPolicyFormat := recformat< name, tame_veto_when_p_divides_kernel, wild_veto >;

DefaultLocalPolicy := rec< LocalPolicyFormat |
    name := "sound",
    tame_veto_when_p_divides_kernel := false,
    wild_veto := false >;

LegacyLocalPolicy := rec< LocalPolicyFormat |
    name := "legacy",
    tame_veto_when_p_divides_kernel := true,
    wild_veto := true >;

IsPPowerOrder := function(m, p)
    return m eq p^Valuation(m, p);
end function;

// phi(D_p): the image in B of the FULL local decomposition group at p,
// generated by the inertia image and by Frobenius.  Used to decide whether
// phi_p factors through the maximal pro-p quotient of G_{Q_p}.
DecompositionImageInBAtPrime := function(ebp, p)
    B := ebp`B; C := ebp`C; f := ebp`f; phi := ebp`phi; d := ebp`d;
    I    := CyclotomicInertiaAtPrime(C, f, d, p);
    frob := CyclotomicFrobeniusAtPrime(C, f, d, p);
    gens := [ phi(t) : t in Generators(I) ] cat [ phi(frob) ];
    return sub< B | gens >;
end function;

// One finite place p | d.  Places not dividing d are unramified in
// Q(mu_d), hence in F, and an unramified phi_v always lifts (send Frobenius
// to any preimage and inertia to 1), so they need no test at all.
LocalVerdictAtPrime := function(ebp, p, policy)
    N := Kernel(ebp`pi);

    Iimg := InertiaImageInBAtPrime(ebp, p);
    if #Iimg eq 1 then
        return LocalVerdictYes, "unramified in F";
    end if;

    Hwild := WildInertiaImageInBAtPrime(ebp, p);

    if #Hwild eq 1 then
        // ---- F/Q tame at p ------------------------------------------------
        ok := IsCyclotomicTameLocallyLiftableAtPrime(ebp, p);
        if ok then
            return LocalVerdictYes, "tame lift exhibited";
        end if;
        if (#N mod p) ne 0 then
            return LocalVerdictNo,
                   "no tame lift, and p does not divide #Ker(pi), so no wild lift exists either";
        end if;
        if policy`tame_veto_when_p_divides_kernel then
            return LocalVerdictNo, "no tame lift (legacy policy: vetoing anyway)";
        end if;
        return LocalVerdictUnknown,
               "no tame lift, but p | #Ker(pi) so a wildly ramified lift is not excluded";
    end if;

    // ---- F/Q wild at p ----------------------------------------------------
    ok := IsCyclotomicWildProPLocallyLiftableAtPrime(ebp, p);
    if ok then
        Dfull := DecompositionImageInBAtPrime(ebp, p);
        if IsPPowerOrder(#Dfull, p) then
            return LocalVerdictYes,
                   "pro-p lift exhibited, and phi_p factors through G_{Q_p}(p)";
        end if;
        return LocalVerdictUnknown,
               "pro-p lift exhibited, but phi_p does not factor through G_{Q_p}(p)";
    end if;
    if policy`wild_veto then
        return LocalVerdictNo, "no pro-p lift (legacy policy: vetoing anyway)";
    end if;
    return LocalVerdictUnknown,
           "no pro-p lift; necessity of the pro-p test for full local liftability is unestablished";
end function;

// The real place is exact in both directions: phi_infinity lifts iff some
// element of order dividing 2 lies over phi(complex conjugation).
LocalVerdictAtRealPlace := function(ebp)
    ok, msg := IsRealLocallyLiftable(ebp);
    if ok then return LocalVerdictYes, msg; end if;
    return LocalVerdictNo, msg;
end function;

// Aggregate.  A single No wins; otherwise a single Unknown wins.
// Second return value is a sequence of <place, verdict, message>, with
// place 0 for the real place.
LocalVerdict := function(ebp, policy)
    reports := [];
    worst := LocalVerdictYes;

    v, msg := LocalVerdictAtRealPlace(ebp);
    Append(~reports, <0, v, msg>);
    if v eq LocalVerdictNo then return LocalVerdictNo, reports; end if;
    if v lt worst then worst := v; end if;

    for q in Factorization(ebp`d) do
        p := q[1];
        v, msg := LocalVerdictAtPrime(ebp, p, policy);
        Append(~reports, <p, v, msg>);
        if v eq LocalVerdictNo then return LocalVerdictNo, reports; end if;
        if v lt worst then worst := v; end if;
    end for;

    return worst, reports;
end function;

// Consumer 1: may this pair still contribute to the b_W upper bound?
LocalTestsAllowPair := function(ebp, policy)
    v := LocalVerdict(ebp, policy);
    return v ne LocalVerdictNo, v;
end function;

// Consumer 2: is the pair PROVEN locally solvable at every place?
LocallySolvableEverywhere := function(ebp, policy)
    v := LocalVerdict(ebp, policy);
    return v eq LocalVerdictYes;
end function;
