#!/usr/bin/env python3
"""Residual witnesses whose closure is E(sqrt W) for a Galois base field E.

Use this when the residual group H has an elementary abelian 2-subgroup D
(typically D = [H,H]) with H/D = Gal(E/Q) for a field E you can write down,
e.g. E = L(sqrt q) with L a cyclic quartic.  The H-field is then E(sqrt W)
for an F2[Gal(E/Q)]-submodule W of E^x/E^x2 of dimension dim D.  When W is
cyclic (generated by one class beta) the H-field is the Galois closure of
E(sqrt beta), so it suffices to search beta.

Strategy: for every subgroup K < Gal(E/Q) compute the classes fixed by K
(linear algebra), and test the beta in that space whose conjugates span
exactly `--dim` dimensions.  Each distinct span W gives one candidate, whose
Galois group and the subgroup fixing sqrt(q) are identified exactly with
PARI's galoisinit (fine for 2-groups).

Found 20T498 ([32,8], dim 2) and 20T583/20T598 ([64,33], dim 3) with
  L = x^4 - x^3 - 54*x^2 + 9*x + 81   (real cyclic quartic, conductor 145)
  S = 2,3,5,29
In both cases L had to be totally real (only the identity of H^ab lifts to an
involution of H) and ramified at 5 (or have 5 split completely): see
gap/local_lift.g.  Choose L by those local tests first.

Example:
  python3 search_abelian_base.py --L "x^4 - x^3 - 54*x^2 + 9*x + 81" \
      --S 2,3,5,29 --dim 2 --group 32,8 --sub 16,6
"""
import argparse
import random
import sys
import time

import numpy as np

import wslib
from wslib import pari


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--L', required=True, help='quartic (or any) polynomial; E = L(sqrt q)')
    ap.add_argument('--q', type=int, default=5, help='E = L(sqrt q); also the quadratic field F (default 5)')
    ap.add_argument('--S', required=True, help='comma-separated primes allowed in the S-units')
    ap.add_argument('--dim', type=int, required=True, help='dimension of W (= rank of the elementary kernel)')
    ap.add_argument('--group', required=True, help='target SmallGroup id of H, e.g. 32,8')
    ap.add_argument('--sub', required=True, help='target id(s) of Gal(K~/Q(sqrt q)), ";"-separated, e.g. "32,7;32,6"')
    ap.add_argument('--zeta', type=int, default=5, help='reject closures containing Q(zeta_m) (0 to disable)')
    ap.add_argument('--per-subgroup', type=int, default=3000, help='max classes tried per fixed space')
    ap.add_argument('--seed', type=int, default=1)
    args = ap.parse_args()

    want = [int(t) for t in args.group.split(',')]
    wantsub = [[int(t) for t in s.split(',')] for s in args.sub.split(';')]
    Sprimes = [int(t) for t in args.S.split(',')]
    rng = random.Random(args.seed)
    t0 = time.time()

    E = pari.polredbest(pari.polcompositum(pari(args.L), pari(f'x^2-({args.q})'))[0])
    base = wslib.GaloisBase(E, Sprimes)
    print(f"E = {E}; {len(base.gens)} S-unit generators; {time.time()-t0:.0f}s", flush=True)

    seen, stats = set(), {}
    for K in base.subgroups():
        if len(K) == base.n:
            continue
        B = base.fixed_space(sorted(K))
        for e in wslib.span_combinations(B, len(base.gens), args.per_subgroup, rng):
            dim, V = base.orbit_span(e)
            if dim != args.dim:
                continue
            key = frozenset(np.packbits(row).tobytes() for row in V)
            if key in seen:
                continue
            seen.add(key)
            M = wslib.quadratic_extension(base.Ey, base.element(e))
            if M is None:
                continue
            try:
                S, gal, gid = wslib.closure_group(M)
            except Exception:
                continue
            stats[tuple(gid)] = stats.get(tuple(gid), 0) + 1
            if gid != want:
                continue
            sub = wslib.subgroup_fixing_sqrt(S, gal, args.q)
            if sub not in wantsub or (args.zeta and wslib.contains_zeta(S, args.zeta)):
                continue
            M = pari.polredabs(M)
            print(f"FOUND {M}\n  coeffs {list(map(int, pari.Vecrev(M)))}\n"
                  f"  group {gid}, Gal(K~/Q(sqrt {args.q})) = {sub}; {time.time()-t0:.0f}s", flush=True)
            return 0
    print("NOT FOUND; closure groups seen:", stats)
    return 1


if __name__ == '__main__':
    sys.exit(main())
